name: solidity_tutorial
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"



dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #web3dart: ^2.3.0
  shared_preferences: ^2.0.7
  flutter_bloc:
  http: ^0.12.1
  get: ^4.6.5
  #url_launcher: wallet_connect: ^1.0.2
  binance_chain: ^0.0.6+1

dev_dependencies:


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - build/contracts/
    - assets/
    - contracts/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
